name: CI Checks
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: Skptak/CI-CD-Github-Actions/formatting@main
        with:
          path: ./
          exclude-dirs: portable, ThirdParty
      - name: Check formatting of MemMang
        uses: Skptak/CI-CD-Github-Actions/formatting@main
        with:
          path: ./portable/MemMang
      - name: Check formatting of Common
        uses: Skptak/CI-CD-Github-Actions/formatting@main
        with:
          path: ./portable/Common

  formatting-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: Skptak/CI-CD-Github-Actions/formatting@main
        with:
            exclude-files: ISR_Support.h

  spell-check:
      runs-on: ubuntu-latest
      steps:
        - name: Clone This Repo
          uses: actions/checkout@v3
        - name: Run spellings check
          uses: Skptak/CI-CD-Github-Actions/rust-spell-check@main
          with:
            path: ./
            exclude-dirs: portable, ThirdParty, docs

        - name: Run spellings check of MemMang
          uses: Skptak/CI-CD-Github-Actions/rust-spell-check@main
          with:
            path: ./portable/MemMang

        - name: Run spellings check of MemMang
          uses: Skptak/CI-CD-Github-Actions/rust-spell-check@main
          with:
            path: ./portable/MemMang

  link-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
      - name: Link Verificication
        uses: Skptak/CI-CD-Github-Actions/link-verifier@main
